### ISSUE TITLE
Confusion about switches DC1 and DC2 ?

### ISSUE THREAD

**Issue by zwrr** [RichiDev/Gotek-Floppy-Disk-Emulator-V2#2]
Hello sir, thank you for creating this project, I am planning to build it for my 386 retro PC, I have a question that I hope you can answer, that is about the switches, I am confused about the role of DC1 and DC2, Hope you can help me, thank you.

**Comment by RichardRozehnal** [comment]
Hello,
vintage floppy drives use pin1 of the floppy connector for disk change signal. If you have such a drive you have to connect this pin 1 to PA14 (JTCK-SWCLK) of he MCU, so you have to set DC1 ON and DC2 OFF. If you have newer drive you have to set DC1 OFF and DC2 ON.

**Comment by zwrr** [comment]
> Hello, vintage floppy drives use pin1 of the floppy connector for disk change signal. If you have such a drive you have to connect this pin 1 to PA14 (JTCK-SWCLK) of he MCU, so you have to set DC1 ON and DC2 OFF. If you have newer drive you have to set DC1 OFF and DC2 ON.

Thank you very much for your answer, I have successfully assembled it and it works perfectly on my 386 retro PC.

![Gotek V2](https://github.com/RichardRozehnal/Gotek-Floppy-Disk-Emulator-V2/assets/59242724/ea12d562-5f10-4d4e-9e48-43c7a423de9c)
