### ISSUE TITLE
jumpers MSX

### ISSUE THREAD

**Issue by FranTerrassa** [RichiDev/Gotek-Floppy-Disk-Emulator-V2#3]
Hello, I have a question, how do they have to put the jumpers to use it on MSX?

**Comment by RichardRozehnal** [comment]
Hi,
have you already tried any settings? Try DC1 OFF and DC2 ON. If it doesn't work, try DC1 ON and DC2 OFF. Unfortunatelly I don't know MSX system. :( Or look at original FlashFloppy page, maybe they have some info about MSX system settings.

**Comment by FranTerrassa** [comment]
Thank you very much for answering, I already have it solved. I leave here the configuration that has worked for me, in case someone needs S1 ON, S0 OFF, JC OFF, J5 OFF, DC2 ON, DC1 OFF.
Thanks and regards.
